#!/usr/bin/env python3
"""
Email Sender Automation Script
Send bulk emails using SMTP with HTML/template support.
"""

import smtplib
import argparse
import csv
import json
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from pathlib import Path
from string import Template


def create_smtp_connection(host, port, username, password, use_tls=True):
    """Create and return an SMTP connection."""
    if use_tls:
        server = smtplib.SMTP(host, port)
        server.starttls()
    else:
        server = smtplib.SMTP(host, port)
    server.login(username, password)
    return server


def load_template(template_file):
    """Load an email template from file."""
    with open(template_file, 'r') as f:
        return Template(f.read())


def send_single_email(server, sender, recipient, subject, body, is_html=False, attachments=None):
    """Send a single email."""
    msg = MIMEMultipart()
    msg['From'] = sender
    msg['To'] = recipient
    msg['Subject'] = subject

    content_type = 'html' if is_html else 'plain'
    msg.attach(MIMEText(body, content_type))

    if attachments:
        for filepath in attachments:
            path = Path(filepath)
            if path.exists():
                with open(filepath, 'rb') as f:
                    part = MIMEBase('application', 'octet-stream')
                    part.set_payload(f.read())
                encoders.encode_base64(part)
                part.add_header('Content-Disposition', f'attachment; filename={path.name}')
                msg.attach(part)

    server.send_message(msg)
    print(f"Email sent to: {recipient}")


def send_bulk_emails(smtp_config, sender, csv_file, template, subject, is_html=True):
    """Send bulk emails using a CSV file with recipient data."""
    server = create_smtp_connection(**smtp_config)

    with open(csv_file, 'r') as f:
        reader = csv.DictReader(f)
        count = 0
        for row in reader:
            email = row.get('email', row.get('Email', ''))
            if not email:
                continue

            # Substitute placeholders in template
            body = template.safe_substitute(row)
            send_single_email(server, sender, email, subject, body, is_html)
            count += 1

    server.quit()
    print(f"\nSent {count} emails successfully.")
    return count


def generate_sample_csv(output_file='recipients.csv'):
    """Generate a sample CSV file for bulk email."""
    sample = """email,name,company
john@example.com,John Smith,Acme Corp
jane@example.com,Jane Doe,Tech Industries
bob@example.com,Bob Wilson,Global Solutions"""
    with open(output_file, 'w') as f:
        f.write(sample)
    print(f"Sample CSV created: {output_file}")
    return output_file


def generate_sample_template(output_file='template.html'):
    """Generate a sample email template."""
    template = """<html>
<body>
    <h2>Hello $name,</h2>
    <p>We hope you're doing well at <strong>$company</strong>!</p>
    <p>This is a personalized message generated by our automation system.</p>
    <p>Best regards,<br>Mr Bubba Services Team</p>
</body>
</html>"""
    with open(output_file, 'w') as f:
        f.write(template)
    print(f"Sample template created: {output_file}")
    return output_file


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Send automated emails')
    subparsers = parser.add_subparsers(dest='command')

    # Single email
    single_parser = subparsers.add_parser('single', help='Send a single email')
    single_parser.add_argument('--host', required=True, help='SMTP host')
    single_parser.add_argument('--port', type=int, default=587, help='SMTP port')
    single_parser.add_argument('--username', required=True, help='SMTP username')
    single_parser.add_argument('--password', required=True, help='SMTP password')
    single_parser.add_argument('--sender', required=True, help='Sender email')
    single_parser.add_argument('--recipient', required=True, help='Recipient email')
    single_parser.add_argument('--subject', required=True, help='Email subject')
    single_parser.add_argument('--body', required=True, help='Email body')
    single_parser.add_argument('--html', action='store_true', help='Send as HTML')
    single_parser.add_argument('--attachments', nargs='+', help='File attachments')

    # Bulk email
    bulk_parser = subparsers.add_parser('bulk', help='Send bulk emails')
    bulk_parser.add_argument('--host', required=True, help='SMTP host')
    bulk_parser.add_argument('--port', type=int, default=587, help='SMTP port')
    bulk_parser.add_argument('--username', required=True, help='SMTP username')
    bulk_parser.add_argument('--password', required=True, help='SMTP password')
    bulk_parser.add_argument('--sender', required=True, help='Sender email')
    bulk_parser.add_argument('--csv', required=True, help='CSV file with recipients')
    bulk_parser.add_argument('--template', required=True, help='Email template file')
    bulk_parser.add_argument('--subject', required=True, help='Email subject')

    # Generate samples
    sample_parser = subparsers.add_parser('sample', help='Generate sample files')
    sample_parser.add_argument('--type', choices=['csv', 'template', 'both'], default='both')

    args = parser.parse_args()

    if args.command == 'single':
        server = create_smtp_connection(args.host, args.port, args.username, args.password)
        send_single_email(server, args.sender, args.recipient, args.subject,
                         args.body, args.html, args.attachments)
        server.quit()

    elif args.command == 'bulk':
        template = load_template(args.template)
        smtp_config = {
            'host': args.host,
            'port': args.port,
            'username': args.username,
            'password': args.password
        }
        send_bulk_emails(smtp_config, args.sender, args.csv, template, args.subject)

    elif args.command == 'sample':
        if args.type in ['csv', 'both']:
            generate_sample_csv()
        if args.type in ['template', 'both']:
            generate_sample_template()
    else:
        parser.print_help()
