#!/usr/bin/env python3
"""
Report Generator Automation Script
Generates reports from CSV/Excel data in various formats (HTML, PDF, Markdown).
"""

import argparse
import csv
import json
from pathlib import Path
from datetime import datetime

try:
    import pandas as pd
    HAS_PANDAS = True
except ImportError:
    HAS_PANDAS = False


def read_data(input_file):
    """Read data from CSV or Excel file."""
    input_path = Path(input_file)
    if not input_path.exists():
        print(f"Error: File '{input_file}' does not exist.")
        return None

    if HAS_PANDAS:
        if input_path.suffix.lower() == '.csv':
            return pd.read_csv(input_file)
        elif input_path.suffix.lower() in ['.xlsx', '.xls']:
            return pd.read_excel(input_file)
        else:
            print("Unsupported file format. Use CSV or Excel.")
            return None
    else:
        # Fallback to csv module
        if input_path.suffix.lower() == '.csv':
            with open(input_file, 'r') as f:
                reader = csv.DictReader(f)
                return list(reader)
        else:
            print("Install pandas for Excel support.")
            return None


def generate_html_report(data, title="Data Report", output_file="report.html"):
    """Generate an HTML report from data."""
    if HAS_PANDAS and isinstance(data, pd.DataFrame):
        table_html = data.to_html(classes='data-table', index=False, border=0)
        summary = data.describe().to_html(classes='summary-table', border=0)
    else:
        if data:
            headers = list(data[0].keys())
            rows = ''.join([
                '<tr>' + ''.join([f'<td>{row[h]}</td>' for h in headers]) + '</tr>'
                for row in data
            ])
            table_html = f'<tr>{"".join([f"<th>{h}</th>" for h in headers])}</tr>{rows}'
            table_html = f'<table class="data-table">{table_html}</table>'
            summary = '<p>Summary statistics require pandas.</p>'
        else:
            table_html = '<p>No data available.</p>'
            summary = ''

    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }}
        .container {{ max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
        h1 {{ color: #333; border-bottom: 2px solid #007bff; padding-bottom: 10px; }}
        h2 {{ color: #555; margin-top: 30px; }}
        .data-table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        .data-table th {{ background: #007bff; color: white; padding: 12px; text-align: left; }}
        .data-table td {{ padding: 10px 12px; border-bottom: 1px solid #ddd; }}
        .data-table tr:nth-child(even) {{ background: #f8f9fa; }}
        .data-table tr:hover {{ background: #e9ecef; }}
        .summary-table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        .summary-table th {{ background: #28a745; color: white; padding: 12px; text-align: left; }}
        .summary-table td {{ padding: 10px 12px; border-bottom: 1px solid #ddd; }}
        .meta {{ color: #888; font-size: 0.9em; margin-top: 30px; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>{title}</h1>
        <p class="meta">Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        <h2>Data Overview</h2>
        {table_html}
        <h2>Summary Statistics</h2>
        {summary}
        <p class="meta">Report generated by Mr Bubba Services - Report Generator</p>
    </div>
</body>
</html>"""

    with open(output_file, 'w') as f:
        f.write(html_content)
    print(f"HTML report saved to: {output_file}")
    return output_file


def generate_markdown_report(data, title="Data Report", output_file="report.md"):
    """Generate a Markdown report from data."""
    if HAS_PANDAS and isinstance(data, pd.DataFrame):
        table_md = data.to_markdown()
        summary_md = data.describe().to_markdown()
    else:
        if data:
            headers = list(data[0].keys())
            header_line = '| ' + ' | '.join(headers) + ' |'
            sep_line = '|' + '|'.join(['---'] * len(headers)) + '|'
            rows = '\n'.join([
                '| ' + ' | '.join([str(row[h]) for h in headers]) + ' |'
                for row in data
            ])
            table_md = f"{header_line}\n{sep_line}\n{rows}"
            summary_md = '*Summary statistics require pandas.*'
        else:
            table_md = '*No data available.*'
            summary_md = ''

    md_content = f"""# {title}

*Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*

## Data Overview

{table_md}

## Summary Statistics

{summary_md}

---
*Report generated by Mr Bubba Services - Report Generator*
"""

    with open(output_file, 'w') as f:
        f.write(md_content)
    print(f"Markdown report saved to: {output_file}")
    return output_file


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Generate reports from data files')
    parser.add_argument('input_file', help='Input CSV or Excel file')
    parser.add_argument('--format', choices=['html', 'md'], default='html',
                        help='Output format')
    parser.add_argument('--title', default='Data Report', help='Report title')
    parser.add_argument('--output', '-o', help='Output file path')

    args = parser.parse_args()
    data = read_data(args.input_file)

    if data is not None:
        if args.format == 'html':
            output = args.output or 'report.html'
            generate_html_report(data, args.title, output)
        else:
            output = args.output or 'report.md'
            generate_markdown_report(data, args.title, output)
